// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import dotenv from "dotenv";
import dotenvExpand from "dotenv-expand"

dotenvExpand.expand(dotenv.config({
  path: ".env.development",
}));

let connectionString = `postgresql://${process.env["POSTGRES_USER"]}:${process.env["POSTGRES_PASSWORD"]}@${process.env["POSTGRES_HOST"]}`;

if (process.env["POSTGRES_PORT"]) {
  connectionString += `:${process.env["POSTGRES_PORT"]}`;
}

connectionString += `/${process.env["POSTGRES_DB"]}?schema=public`;

if (process.env.NODE_ENV === "production") {
  connectionString += "&sslmode=require";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: connectionString,
  },
});
