// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

let connectionString = `postgresql://${process.env["POSTGRES_USER"]}:${process.env["POSTGRES_PASSWORD"]}@${process.env["POSTGRES_HOST"]}`;

if (process.env["POSTGRES_PORT"]) {
  connectionString += `:${process.env["POSTGRES_PORT"]}`;
}

connectionString += `/${process.env["POSTGRES_DB"]}?schema=public`;

console.log(process.env.NODE_ENV);
console.log(process.env.NODE_ENV === "production");
if (process.env.NODE_ENV === "production") {
  connectionString += "&sslmode=require";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: connectionString,
  },
});
