// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import dotenv from "dotenv";
import dotenvExpand from "dotenv-expand"

dotenvExpand.expand(dotenv.config({
  path: ".env.development",
}));

let baseString = `postgresql://${process.env["POSTGRES_USER"]}:${process.env["POSTGRES_PASSWORD"]}@${process.env["POSTGRES_HOST"]}`;

if (process.env["POSTGRES_PORT"]) {
  baseString += `:${process.env["POSTGRES_PORT"]}`;
}

// Note: ?schema=public is NOT used here — Prisma 7's prisma.config.ts parses
// the URL differently and including it corrupts the shadow database schema path.
let connectionString = `${baseString}/${process.env["POSTGRES_DB"]}`;
let shadowDatabaseConnectionString = `${baseString}/${process.env["POSTGRES_DB"]}_shadow`;

if (process.env.NODE_ENV === "production") {
  connectionString += "?sslmode=require";
  shadowDatabaseConnectionString += "?sslmode=require";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: connectionString,
    shadowDatabaseUrl: shadowDatabaseConnectionString,
  },
});
