name: Linting

on:
  pull_request:
  push:
    branches: [main, feat/gift-card-test-checkout]
  workflow_dispatch:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - run: npm ci

      - run: npm run lint:prettier:check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - run: npm ci

      - run: npm run lint:eslint:check

  commitlint:
    name: Commitlint
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - run: npm ci

      - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
